### ISSUE TITLE
Add Dependabot configuration

### ISSUE THREAD

**Issue by mbentz-uf** [ctsit/report_handler#14]
Add Dependabot configuration in `.github/dependabot.yml` to generate PRs when submodules update. The configuration should be:
```yaml
version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: "daily"
    target-branch: "develop"
```
